### ISSUE TITLE
Estimated date of birth issues

### ISSUE THREAD

**Issue by fenjb** [WorldHealthOrganization/smart-emcare#55]
When selected 'date of birth not known' and then 'estimated age of estimated dob; = est. age in yrs & months (2 months or older), then put cursor in month box, app crashes.
APK 1.0.9_dev; bundle 1.0.1.rc12.build.73

In previous version (not sure bundle / apk), there was no crash, but an issue with estimated age was that no constraint on months / years (e.g. could enter 12 months and 1 year --> 24 months - risk that this confuses provider) - suggest constrain months to 11 and years to 4

**Comment by kaledip** [comment]
@ppanchal-argus  @delcroip  the app crashes for me too once I start entering anything in textbox "Age in months" or "Age in years".

**Comment by ppanchal-argus** [comment]
@delcroip Overall it is crashing while executing the FhirPath Expression, with the following stacktrace. Can you give this a look?
2023-02-20 20:57:38.724 12652-12652/com.argusoft.who.emcare E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at org.hl7.fhir.r4.utils.FHIRPathEngine.dateAdd(FHIRPathEngine.java:2006)
        at org.hl7.fhir.r4.utils.FHIRPathEngine.opMinus(FHIRPathEngine.java:2234)
        at org.hl7.fhir.r4.utils.FHIRPathEngine.operate(FHIRPathEngine.java:1432)
        at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1189)
        at org.hl7.fhir.r4.utils.FHIRPathEngine.evaluate(FHIRPathEngine.java:577)
        at com.google.android.fhir.datacapture.fhirpath.ExpressionEvaluator.evaluateVariable(ExpressionEvaluator.kt:389)
        at com.google.android.fhir.datacapture.fhirpath.ExpressionEvaluator.evaluateQuestionnaireVariableExpression$datacapture_release(ExpressionEvaluator.kt:257)
        at com.google.android.fhir.datacapture.fhirpath.ExpressionEvaluator.findAndEvaluateVariable(ExpressionEvaluator.kt:313)
        at com.google.android.fhir.datacapture.fhirpath.ExpressionEvaluator.extractDependentVariables$datacapture_release(ExpressionEvaluator.kt:209)
        at com.google.android.fhir.datacapture.fhirpath.ExpressionEvaluator.evaluateCalculatedExpressions(ExpressionEvaluator.kt:112)
        at com.google.android.fhir.datacapture.QuestionnaireViewModel.updateDependentQuestionnaireResponseItems(QuestionnaireViewModel.kt:390)
        at com.google.android.fhir.datacapture.QuestionnaireViewModel.access$updateDependentQuestionnaireResponseItems(QuestionnaireViewModel.kt:56)
        at com.google.android.fhir.datacapture.QuestionnaireViewModel$answersChangedCallback$1.invoke(QuestionnaireViewModel.kt:267)
        at com.google.android.fhir.datacapture.QuestionnaireViewModel$answersChangedCallback$1.invoke(QuestionnaireViewModel.kt:247)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemViewItem.setAnswer(QuestionnaireItemViewItem.kt:122)

**Comment by delcroip** [comment]
@ppanchal-argus thanks i missed that bug, i will have a look

**Comment by delcroip** [comment]
Fixed using the calandar-unit codesystem (UCUM not supported for month and year by the HL7 Libs)

**Comment by kaledip** [comment]
Able to add months and years.Retested with latest build
